package generate

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const generatedHeader = `# Generated by Ghega — DO NOT EDIT MANUALLY
# https://github.com/ghega/ghega
# Timestamp: %s
`

// RunChannelGenerate generates a channel scaffold for the given channel type.
func RunChannelGenerate(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: ghega generate channel <type>")
	}

	channelType := args[0]
	remaining := args[1:]

	switch channelType {
	case "mllp-to-http":
		return runGenerateMLLPToHTTP(remaining)
	default:
		return fmt.Errorf("unknown channel type: %s", channelType)
	}
}

func runGenerateMLLPToHTTP(args []string) error {
	fs := flag.NewFlagSet("mllp-to-http", flag.ExitOnError)
	name := fs.String("name", "", "Channel name (required)")
	messageType := fs.String("message-type", "ADT_A01", "HL7v2 message type")
	out := fs.String("out", "", "Output directory (required)")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if *name == "" {
		return fmt.Errorf("--name is required")
	}
	if *out == "" {
		return fmt.Errorf("--out is required")
	}

	return generateMLLPToHTTP(*name, *messageType, *out)
}

func generateMLLPToHTTP(name, messageType, outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outDir, "tests"), 0755); err != nil {
		return fmt.Errorf("creating tests directory: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outDir, "fixtures"), 0755); err != nil {
		return fmt.Errorf("creating fixtures directory: %w", err)
	}

	timestamp := time.Now().UTC().Format(time.RFC3339)

	channelYAML := fmt.Sprintf(`%sname: %s
description: MLLP to HTTP channel for %s messages
source:
  type: mllp
  config:
    host: 0.0.0.0
    port: 2575
destination:
  type: http
  config:
    url: http://example.com/webhook
    method: POST
mappings:
  - source: PID-3.1
    target: patient_mrn
    transform: copy
  - source: PID-5.1
    target: last_name
    transform: copy
  - source: PID-5.2
    target: first_name
    transform: copy
  - source: MSH-9.1
    target: message_type
    transform: copy
tests:
  - name: basic-pass
    description: Validates that all four mappings extract the correct values from a valid HL7 message.
    input: fixtures/sample.hl7
    expected:
      patient_mrn: SYNTHETIC_MRN_123456
      last_name: TESTPATIENT
      first_name: SYNTHETIC
      message_type: ADT
  - name: invalid-input-handling
    description: Verifies that the channel gracefully handles malformed HL7 input.
    input: NOT_A_VALID_HL7_MESSAGE
    expected: {}
    expectError: true
policies:
  network:
    allowedHosts:
      - example.com
  payload:
    maxSizeBytes: 1048576
  time:
    maxProcessingSeconds: 30
`, fmt.Sprintf(generatedHeader, timestamp), name, messageType)

	if err := os.WriteFile(filepath.Join(outDir, "channel.yaml"), []byte(channelYAML), 0644); err != nil {
		return fmt.Errorf("writing channel.yaml: %w", err)
	}

	testFixture := fmt.Sprintf(`%sname: fixture-example
description: Example test fixture that can be copied into channel.yaml tests.
input: fixtures/sample.hl7
expected:
  patient_mrn: SYNTHETIC_MRN_123456
  last_name: TESTPATIENT
  first_name: SYNTHETIC
  message_type: ADT
`, fmt.Sprintf(generatedHeader, timestamp))

	if err := os.WriteFile(filepath.Join(outDir, "tests", "fixture.yaml"), []byte(testFixture), 0644); err != nil {
		return fmt.Errorf("writing tests/fixture.yaml: %w", err)
	}

	hl7Message := buildSyntheticHL7(messageType)
	if err := os.WriteFile(filepath.Join(outDir, "fixtures", "sample.hl7"), []byte(hl7Message), 0644); err != nil {
		return fmt.Errorf("writing fixtures/sample.hl7: %w", err)
	}

	return nil
}

func buildSyntheticHL7(messageType string) string {
	// All data is synthetic and clearly marked as such.
	// No real patient names, addresses, or identifiers are used.
	segments := []string{
		fmt.Sprintf("MSH|^~\\&|GHEGA_SENDER|GHEGA_FACILITY|GHEGA_RECEIVER|GHEGA_FACILITY|%s||%s|12345|P|2.5", time.Now().UTC().Format("20060102150405"), strings.Replace(messageType, "_", "^", 1)),
		"EVN|A01|20240101000000|||",
		"PID|1||SYNTHETIC_MRN_123456^^^GHEGA_FACILITY^MR||TESTPATIENT^SYNTHETIC||19800101|M|||123 SYNTHETIC STREET^^SYNTHETIC CITY^ST^12345||555-0100||||||||||||||||||||",
		"PV1|1|I|GHEGA_WARD^GHEGA_ROOM^1||||||||||||||||||||||||||||||||||||||||||20240101000000",
	}
	return strings.Join(segments, "\r") + "\r"
}
