package generate

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/sroopra/ghega/pkg/fhir"
	"github.com/sroopra/ghega/pkg/mapping"
)

const generatedHeader = `# Generated by Ghega — DO NOT EDIT MANUALLY
# https://github.com/ghega/ghega
# Timestamp: %s
`

// RunChannelGenerate generates a channel scaffold for the given channel type.
func RunChannelGenerate(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: ghega generate channel <type>")
	}

	channelType := args[0]
	remaining := args[1:]

	switch channelType {
	case "mllp-to-http":
		return runGenerateMLLPToHTTP(remaining)
	case "hl7v2-to-fhir":
		return runGenerateHL7v2ToFHIR(remaining)
	default:
		return fmt.Errorf("unknown channel type: %s", channelType)
	}
}

func runGenerateMLLPToHTTP(args []string) error {
	fs := flag.NewFlagSet("mllp-to-http", flag.ExitOnError)
	name := fs.String("name", "", "Channel name (required)")
	messageType := fs.String("message-type", "ADT_A01", "HL7v2 message type")
	out := fs.String("out", "", "Output directory (required)")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if *name == "" {
		return fmt.Errorf("--name is required")
	}
	if *out == "" {
		return fmt.Errorf("--out is required")
	}

	return generateMLLPToHTTP(*name, *messageType, *out)
}

func generateMLLPToHTTP(name, messageType, outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outDir, "tests"), 0755); err != nil {
		return fmt.Errorf("creating tests directory: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outDir, "fixtures"), 0755); err != nil {
		return fmt.Errorf("creating fixtures directory: %w", err)
	}

	timestamp := time.Now().UTC().Format(time.RFC3339)

	channelYAML := fmt.Sprintf(`%sname: %s
description: Generated ADT A01 MLLP to HTTP channel
source:
  type: mllp
  config:
    host: 0.0.0.0
    port: 2575
destination:
  type: http
  config:
    url: http://example.com/webhook
    method: POST
    timeout: 30
mappings:
  - source: PID-3.1
    target: patient_mrn
  - source: PID-5.1
    target: patient_last_name
  - source: PID-5.2
    target: patient_first_name
  - source: MSH-9.1
    target: message_type
tests:
  - name: valid_adt_a01
    description: A valid ADT A01 message should map all fields
    input: fixtures/sample.hl7
    expected:
      patient_mrn: SYNTHETIC_MRN_123456
      patient_last_name: TESTPATIENT
      patient_first_name: SYNTHETIC
      message_type: ADT
  - name: missing_pid_segment
    description: A message without PID should still produce message_type
    input: fixtures/minimal.hl7
    expected:
      message_type: ADT
policies:
  network:
    allowedHosts:
      - example.com
  payload:
    maxSizeBytes: 1048576
  time:
    maxProcessingSeconds: 30
`, fmt.Sprintf(generatedHeader, timestamp), name)

	if err := os.WriteFile(filepath.Join(outDir, "channel.yaml"), []byte(channelYAML), 0644); err != nil {
		return fmt.Errorf("writing channel.yaml: %w", err)
	}

	testFixture := fmt.Sprintf(`%s# Test fixtures for %s
# Fixtures are loaded from the fixtures/ directory.
`, fmt.Sprintf(generatedHeader, timestamp), name)

	if err := os.WriteFile(filepath.Join(outDir, "tests", "fixture.yaml"), []byte(testFixture), 0644); err != nil {
		return fmt.Errorf("writing tests/fixture.yaml: %w", err)
	}

	hl7Message := buildSyntheticHL7(messageType)
	if err := os.WriteFile(filepath.Join(outDir, "fixtures", "sample.hl7"), []byte(hl7Message), 0644); err != nil {
		return fmt.Errorf("writing fixtures/sample.hl7: %w", err)
	}

	minimalHL7 := buildMinimalHL7(messageType)
	if err := os.WriteFile(filepath.Join(outDir, "fixtures", "minimal.hl7"), []byte(minimalHL7), 0644); err != nil {
		return fmt.Errorf("writing fixtures/minimal.hl7: %w", err)
	}

	return nil
}

func runGenerateHL7v2ToFHIR(args []string) error {
	fs := flag.NewFlagSet("hl7v2-to-fhir", flag.ExitOnError)
	name := fs.String("name", "", "Channel name (required)")
	messageType := fs.String("message-type", "ADT_A01", "HL7v2 message type")
	out := fs.String("out", "", "Output directory (required)")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if *name == "" {
		return fmt.Errorf("--name is required")
	}
	if *out == "" {
		return fmt.Errorf("--out is required")
	}

	return generateHL7v2ToFHIR(*name, *messageType, *out)
}

func generateHL7v2ToFHIR(name, messageType, outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outDir, "tests"), 0755); err != nil {
		return fmt.Errorf("creating tests directory: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outDir, "fixtures"), 0755); err != nil {
		return fmt.Errorf("creating fixtures directory: %w", err)
	}

	timestamp := time.Now().UTC().Format(time.RFC3339)

	channelYAML := fmt.Sprintf(`%sname: %s
description: Generated HL7v2 to FHIR channel
source:
  type: mllp
  config:
    host: 0.0.0.0
    port: 2575
destination:
  type: fhir
  config:
    url: http://example.com/fhir
    method: POST
    timeout: 30
mappings:
  - source: PID-3.1
    target: patient_mrn
  - source: PID-5.1
    target: patient_last_name
  - source: PID-5.2
    target: patient_first_name
  - source: MSH-9.1
    target: message_type
tests:
  - name: valid_adt_a01
    description: A valid ADT A01 message should produce a FHIR Bundle
    input: fixtures/sample.hl7
    expectedJSON: fixtures/expected.json
policies:
  network:
    allowedHosts:
      - example.com
  payload:
    maxSizeBytes: 1048576
  time:
    maxProcessingSeconds: 30
`, fmt.Sprintf(generatedHeader, timestamp), name)

	if err := os.WriteFile(filepath.Join(outDir, "channel.yaml"), []byte(channelYAML), 0644); err != nil {
		return fmt.Errorf("writing channel.yaml: %w", err)
	}

	testFixture := fmt.Sprintf(`%s# Test fixtures for %s
# Fixtures are loaded from the fixtures/ directory.
`, fmt.Sprintf(generatedHeader, timestamp), name)

	if err := os.WriteFile(filepath.Join(outDir, "tests", "fixture.yaml"), []byte(testFixture), 0644); err != nil {
		return fmt.Errorf("writing tests/fixture.yaml: %w", err)
	}

	hl7Message := buildSyntheticHL7(messageType)
	if err := os.WriteFile(filepath.Join(outDir, "fixtures", "sample.hl7"), []byte(hl7Message), 0644); err != nil {
		return fmt.Errorf("writing fixtures/sample.hl7: %w", err)
	}

	expectedJSON, err := buildExpectedFHIRJSON(hl7Message)
	if err != nil {
		return fmt.Errorf("building expected FHIR JSON: %w", err)
	}
	if err := os.WriteFile(filepath.Join(outDir, "fixtures", "expected.json"), []byte(expectedJSON), 0644); err != nil {
		return fmt.Errorf("writing fixtures/expected.json: %w", err)
	}

	return nil
}

// buildExpectedFHIRJSON runs the real FHIR mapping engine on the given HL7
// message and returns the resulting Bundle as pretty-printed JSON.
func buildExpectedFHIRJSON(hl7Message string) (string, error) {
	eng := mapping.NewFHIREngine()
	bundle, err := eng.Apply([]byte(hl7Message))
	if err != nil {
		return "", fmt.Errorf("fhir engine: %w", err)
	}
	bundleJSON, err := fhir.BundleToJSON(bundle)
	if err != nil {
		return "", fmt.Errorf("marshal bundle: %w", err)
	}
	var pretty json.RawMessage
	if err := json.Unmarshal(bundleJSON, &pretty); err != nil {
		return "", fmt.Errorf("unmarshal for re-format: %w", err)
	}
	formatted, err := json.MarshalIndent(pretty, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal indent: %w", err)
	}
	return string(formatted) + "\n", nil
}

func buildSyntheticHL7(messageType string) string {
	// All data is synthetic and clearly marked as such.
	// No real patient names, addresses, or identifiers are used.
	hl7Type := strings.Replace(messageType, "_", "^", 1)
	segments := []string{
		fmt.Sprintf("MSH|^~\\&|GHEGA_SENDER|GHEGA_FACILITY|GHEGA_RECEIVER|GHEGA_FACILITY|%s||%s|12345|P|2.5", time.Now().UTC().Format("20060102150405"), hl7Type),
		"EVN|A01|20240101000000|||",
		"PID|1||SYNTHETIC_MRN_123456^^^GHEGA_FACILITY^MR||TESTPATIENT^SYNTHETIC||19800101|M|||123 SYNTHETIC STREET^^SYNTHETIC CITY^ST^12345||555-0100||||||||||||||||||||",
		"PV1|1|I|GHEGA_WARD^GHEGA_ROOM^1||||||||||||||||||||||||||||||||||||||||||20240101000000",
	}
	return strings.Join(segments, "\r") + "\r"
}

func buildMinimalHL7(messageType string) string {
	// Minimal HL7 message with only MSH and EVN — no PID segment.
	hl7Type := strings.Replace(messageType, "_", "^", 1)
	segments := []string{
		fmt.Sprintf("MSH|^~\\&|GHEGA_SENDER|GHEGA_FACILITY|GHEGA_RECEIVER|GHEGA_FACILITY|%s||%s|12346|P|2.5", time.Now().UTC().Format("20060102150405"), hl7Type),
		"EVN|A01|20240101000000|||",
	}
	return strings.Join(segments, "\r") + "\r"
}
