package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/sroopra/ghega/pkg/migration"
)

func TestRunMigrationTaskGenerate_MissingChannel(t *testing.T) {
	err := RunMigrationTaskGenerate([]string{"--out", "/tmp/test-out.yaml"})
	if err == nil {
		t.Fatal("expected error for missing --channel")
	}
	if !strings.Contains(err.Error(), "--channel is required") {
		t.Errorf("expected error to mention --channel, got: %v", err)
	}
}

func TestRunMigrationTaskGenerate_MissingOut(t *testing.T) {
	err := RunMigrationTaskGenerate([]string{"--channel", "my-channel"})
	if err == nil {
		t.Fatal("expected error for missing --out")
	}
	if !strings.Contains(err.Error(), "--out is required") {
		t.Errorf("expected error to mention --out, got: %v", err)
	}
}

func TestGenerateMigrationTask_CreatesYAMLFile(t *testing.T) {
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, "rewrite-tasks.yaml")

	err := RunMigrationTaskGenerate([]string{
		"--channel", "my-channel",
		"--out", outPath,
		"--category", "conditional",
		"--severity", "high",
		"--description", "Replace conditional logic with CEL expression",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("reading output file: %v", err)
	}

	if !strings.Contains(string(data), "Generated by Ghega") {
		t.Errorf("expected file to contain 'Generated by Ghega' header")
	}

	var tasks []migration.RewriteTaskItem
	if err := yaml.Unmarshal(data, &tasks); err != nil {
		t.Fatalf("unmarshal rewrite tasks: %v", err)
	}

	if len(tasks) != 1 {
		t.Fatalf("expected 1 task, got %d", len(tasks))
	}

	task := tasks[0]
	if task.Severity != "high" {
		t.Errorf("severity = %q, want high", task.Severity)
	}
	if task.Description != "Replace conditional logic with CEL expression" {
		t.Errorf("description = %q, want 'Replace conditional logic with CEL expression'", task.Description)
	}
	if task.Category != "conditional" {
		t.Errorf("category = %q, want conditional", task.Category)
	}
}

func TestGenerateMigrationTask_DefaultSeverityAndDescription(t *testing.T) {
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, "rewrite-tasks.yaml")

	err := RunMigrationTaskGenerate([]string{
		"--channel", "my-channel",
		"--out", outPath,
		"--category", "loop",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("reading output file: %v", err)
	}

	var tasks []migration.RewriteTaskItem
	if err := yaml.Unmarshal(data, &tasks); err != nil {
		t.Fatalf("unmarshal rewrite tasks: %v", err)
	}

	if len(tasks) != 1 {
		t.Fatalf("expected 1 task, got %d", len(tasks))
	}

	task := tasks[0]
	if task.Severity != "medium" {
		t.Errorf("severity = %q, want medium", task.Severity)
	}
	if task.Description != "Replace loop with collection mapping or iteration" {
		t.Errorf("description = %q, want default loop description", task.Description)
	}
}

func TestGenerateMigrationTask_NoCategoryNoDescription(t *testing.T) {
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, "rewrite-tasks.yaml")

	err := RunMigrationTaskGenerate([]string{
		"--channel", "my-channel",
		"--out", outPath,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("reading output file: %v", err)
	}

	var tasks []migration.RewriteTaskItem
	if err := yaml.Unmarshal(data, &tasks); err != nil {
		t.Fatalf("unmarshal rewrite tasks: %v", err)
	}

	if len(tasks) != 1 {
		t.Fatalf("expected 1 task, got %d", len(tasks))
	}

	task := tasks[0]
	if task.Severity != "medium" {
		t.Errorf("severity = %q, want medium", task.Severity)
	}
	if task.Description != "Manual rewrite required" {
		t.Errorf("description = %q, want 'Manual rewrite required'", task.Description)
	}
	if task.Category != "" {
		t.Errorf("category = %q, want empty", task.Category)
	}
}

func TestGenerateMigrationTask_ContainsChannelName(t *testing.T) {
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, "rewrite-tasks.yaml")

	err := RunMigrationTaskGenerate([]string{
		"--channel", "adt-a01-feed",
		"--out", outPath,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("reading output file: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Channel: adt-a01-feed") {
		t.Errorf("expected header to contain channel name")
	}
}
