package generate

import (
	"flag"
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/sroopra/ghega/pkg/migration"
)

const rewriteTaskHeader = `# Generated by Ghega — DO NOT EDIT MANUALLY
# https://github.com/ghega/ghega
# Channel: %s
# Timestamp: %s
`

// RunMigrationTaskGenerate generates a rewrite-tasks.yaml file for a channel.
func RunMigrationTaskGenerate(args []string) error {
	fs := flag.NewFlagSet("migration-task", flag.ExitOnError)
	channelName := fs.String("channel", "", "Channel name (required)")
	outPath := fs.String("out", "", "Output file path (required)")
	category := fs.String("category", "", "Pattern category (e.g. conditional, loop, channel_map_access)")
	severity := fs.String("severity", "medium", "Severity level: low, medium, or high")
	description := fs.String("description", "", "Description of the rewrite task")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if *channelName == "" {
		return fmt.Errorf("--channel is required")
	}
	if *outPath == "" {
		return fmt.Errorf("--out is required")
	}

	return generateMigrationTask(*channelName, *outPath, *category, *severity, *description)
}

func generateMigrationTask(channelName, outPath, category, severity, description string) error {
	timestamp := time.Now().UTC().Format(time.RFC3339)

	task := migration.RewriteTaskItem{
		Severity:    severity,
		Description: description,
		Category:    category,
	}

	if task.Description == "" {
		// Provide a sensible default description based on category.
		switch category {
		case "conditional":
			task.Description = "Replace conditional logic with CEL expression"
		case "loop":
			task.Description = "Replace loop with collection mapping or iteration"
		case "channel_map_access":
			task.Description = "Replace channelMap access with channel configuration or mapping"
		case "logger":
			task.Description = "Replace logger call with structured logging"
		case "destination_dispatch":
			task.Description = "Replace destination dispatch with destination configuration"
		case "response_map_access":
			task.Description = "Replace responseMap with Ghega destination response handling or custom Go logic"
		case "external_call":
			task.Description = "Replace external call with integration step or policy"
		case "e4x_manipulation":
			task.Description = "Replace E4X manipulation with mapping or transformation"
		default:
			task.Description = "Manual rewrite required"
		}
	}

	tasks := []migration.RewriteTaskItem{task}

	data, err := yaml.Marshal(tasks)
	if err != nil {
		return fmt.Errorf("marshal rewrite tasks: %w", err)
	}

	content := fmt.Sprintf(rewriteTaskHeader, channelName, timestamp) + string(data)

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write rewrite tasks file: %w", err)
	}

	return nil
}
